#!/bin/bash
# Pyramid OpenShift post-deploy pre-start configuration

APP=spacehub

source ~/python/bin/activate_virtenv

# Have apache serve up all of our static resources
echo "Symlinking static resources from $APP/public"
ln -s $OPENSHIFT_REPO_DIR/wsgi/$APP/$APP/static/* $OPENSHIFT_REPO_DIR/wsgi/static/

cd $OPENSHIFT_REPO_DIR/wsgi/$APP

# We're not doing 'install' to save space.
python setup.py develop
