#!/bin/bash
# Pyramid OpenShift post-deploy pre-start configuration

APP=spacehub

source ~/python/bin/activate_virtenv

cd $OPENSHIFT_REPO_DIR/wsgi/$APP

# Initialize our database
if [ ! -e $OPENSHIFT_DATA_DIR/DB_INITIALIZED ]; then
    echo "Initializing database"
    paster setup-app production.ini
    touch $OPENSHIFT_DATA_DIR/DB_INITIALIZED
fi

# Run the test suite automatically
# At the moment failure does not prevent the code from getting deployed
echo "Running the test suite"
unset OPENSHIFT_APP_NAME
python setup.py test
